### ISSUE TITLE
Problem with Settings.ColorPicker in 0PluginLibrary

### ISSUE THREAD

**Issue by Japanese-Schoolgirl** [rauenzi/BDPluginLibrary#102]
When trying to create ColorPicker from Settings the following error appears:
![Screenshot of that error](https://user-images.githubusercontent.com/27737525/139533012-4bdc6c1b-7f32-4b3a-a7ba-48b54c95a844.png)
ZeresPluginLibrary version: 1.2.33, tested on Discord Canary on Win10 (64-bit) OS
For fast error reproducing the following code can be used:
```
var { Settings } = ZeresPluginLibrary;
var test = document.createElement('div');
new Settings.SettingGroup('test', { shown:true }).appendTo(test).append(new Settings.ColorPicker('test', 'test', '#fff', (e)=>console.log(e)));
document.querySelector('div').append(test);
```
P.S. The problem itself isn't critical and ColorPicker is easily replaced with regular input of color, but I think it's better to inform about it, if it hasn't been done already

**Comment by rauenzi** [comment]
This has been fixed.
