### ISSUE TITLE
I can't download it.

### ISSUE THREAD

**Issue by Loli-Kyn** [rauenzi/BDPluginLibrary#114]
I follow the link and an error pops up
![Скриншот 23-01-2022 212112](https://user-images.githubusercontent.com/52761837/150692358-e6570239-a2c0-4dd9-ab06-ffd7f466c6c4.png)
![Скриншот 23-01-2022 211859](https://user-images.githubusercontent.com/52761837/150692368-c5146ee3-814b-46a2-b19b-cfda449d6c9c.png)

**Comment by Nagol12344** [comment]
you can download it from here [https://betterdiscord.app/plugin/ZeresPluginLibrary](https://betterdiscord.app/plugin/ZeresPluginLibrary)
