### ISSUE TITLE
Why removed DiscordAPI module from ZeresPluginLibrary?

### ISSUE THREAD

**Issue by matvey2207-new** [rauenzi/BDPluginLibrary#115]
The ZeresPluginLibrary changelog says that the DiscordApi module was removed, several of my plugins worked on it. Why was DiscordApi removed, and how can it be replaced?
Thanks in advance for your reply!

**Comment by rauenzi** [comment]
It was removed because it was very unstable, terribly structured and was deprecated with notice in 2020.

You can use Discord's internal modules yourself to perform some of the same operations.

**Comment by rauenzi** [comment]
You can also see the documentation for more information on what has changed for developers including new deprecations
