### ISSUE TITLE
Why the hell does it (without consent) reinstall itself when changes are made to the js.

### ISSUE THREAD

**Issue by ohitstom** [rauenzi/BDPluginLibrary#117]
So im using a patch for your pluginlibrary that re-adds discords api in a pretty patched way but it works. This is because a couple of my plugins rely on discords api.

So tell me why the hell, when i edit the js in my plugins folder (with discord closed) does it detect this on launch, offer me the CHOICE to update. Then regardless it will restart discord and force the update, even if you deny the update.

Surely that breaks major security concerns.

**Comment by rauenzi** [comment]
Your plugins should not have been relying on a module that was deprecated in 2020. And I have no idea what you're referring to. It only prompts for update if the remote version is greater than the local version. It does not force the update, it puts the banner at the top that you need to click to update the plugin. You can review the code to see this.

**Comment by bygalacos** [comment]
Yeah, even your script set to read-only mode it somehow updates. But no worries check my fork to get fixed version https://github.com/bygalacos/OnesPluginLibrary/blob/main/0PluginLibrary.plugin.js
