### ISSUE TITLE
Crashing when rightclicking on ppl in vc

### ISSUE THREAD

**Issue by MrZeroLord** [rauenzi/BDPluginLibrary#119]
‌​​‌​‌​​‌‌​‌​‌‌​​‌‌​​​‌​‌‌​​​‌​​‌​​‌​‌‌​‌‌​‌‌‌‌​‌‌​‌​​​​‌‌‌​​​
![Jk1bKohp](https://user-images.githubusercontent.com/40106969/155155510-87c7cd18-670d-4218-9626-8eae7b04dd74.png)
​
crash by rightclicking onto there

![AN8NG1TB](https://user-images.githubusercontent.com/40106969/155156486-47c650c8-24e3-45dc-a61e-caebd7aebb2f.png)

**Comment by rauenzi** [comment]
This is not for powercord.
