### ISSUE TITLE
Context Menus

### ISSUE THREAD

**Issue by FlexGamesGitHub** [rauenzi/BDPluginLibrary#122]
(I got no big clue of it and am just trying to get this working because there isn't a real tutorial as well as no support anywhere so it could be that this is no real issue/bug) (also I am not soo familiar with JS)

I tried different Things to get this working but everything cause this error to occur:
```javascript
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Function.escapeID (betterdiscord://plugins/0PluginLibrary.plugin.js:814)
    at Function.buildMenuItem (betterdiscord://plugins/0PluginLibrary.plugin.js:4387)
    at mapper (betterdiscord://plugins/0PluginLibrary.plugin.js:4440)
    at Array.map (<anonymous>)
    at Function.buildMenuChildren (betterdiscord://plugins/0PluginLibrary.plugin.js:4446)
```

My elements for the build are currently made like this:
```
for (var categ ...) {
    categs.push(DCM.buildMenuItem({
            type: "toggle",
            label: categ,
            active: data[categ].users.includes(evt.currentTarget.getAttribute('user-id')) ? true : false,
            action: (v) => { v ? json_d_w(['fr_ca', categ, "users"], json_d_r(["fr_ca", categ, "users"]).push(evt.currentTarget.getAttribute('user-id'))) : null }
    }));
}
```
And the context menu like this
```js
DCM.openContextMenu(evt, DCM.buildMenu(DCM.buildMenuChildren([categs])));
```
This all is based on a database and a click event which should open this context menu, type, label, active (and action should also be but I can't really prove it is) is given for all categs

**Comment by rauenzi** [comment]
You are pre-building the menu items before tossing them into `buildMenuChildren` which is not supported. Please see the documentation for how the function is used. https://rauenzi.github.io/BDPluginLibrary/docs/module-DiscordContextMenu.html#.buildMenuChildren

**Comment by FlexGamesGitHub** [comment]
The docs don't help me far.. I now tried removing `DCM.buildMenuItem` and also removed `DCM.buildMenuChildren` just for testing if I didn't understand something right but it didn't help and I still don't understand how this should work 😅

**Comment by FlexGamesGitHub** [comment]
Well I came to a point now, where I have this thing of trial and error and seem to have tried everything I can imagine:
```js
// var categs = {
//             type: "toggle",
//             label: data[0].name,
//             active: data[0].users.includes(evt.currentTarget.getAttribute('dm-id')) ? true : false,
//             action: v => { if(v) json_d_w(['friend_categories', 0, "users"], json_d_r(["friend_categories", 0, "users"]).push(evt.currentTarget.getAttribute('dm-id'))) }
//         };
// data = json_d_r(['friend_categories']);

// for (i = 0; i < data.length; i++) {
//     categs.push(DCM.buildMenuItem({
//         type: "toggle",
//         label: data[i].name,
//         active: data[i].users.includes(evt.currentTarget.getAttribute('dm-id')) ? true : false,
//         action: v => { if(v) json_d_w(['friend_categories', i, "users"], json_d_r(["friend_categories", i, "users"]).push(evt.currentTarget.getAttribute('dm-id'))) }
//     }));
// }
console.log(DCM.buildMenu(DCM.buildMenuChildren([{
    label: "Menu Item",
    action: () => {console.log("MENU ITEM");}
}])))
DCM.openContextMenu(evt, DCM.buildMenu(DCM.buildMenuChildren([{
    label: "Menu Item",
    action: () => {console.log("MENU ITEM");}
}], {align: "bottom"})));

// console.log(categs)

// DCM.openContextMenu(evt, categs, {align: "bottom"});
```
I went through the error mentioned above and trying to resolve it ended in the React error `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`. Trying to resolve this gets me back to the above-mentioned error. 

So could you please now explain how in the world this works?
