### ISSUE TITLE
Settings.Slider renders a value of 10, ignoring actual value

### ISSUE THREAD

**Issue by planetarian** [rauenzi/BDPluginLibrary#13]
On any instance of Settings.Slider, when rendering the slider, the current setting is ignored, and the settings panel opens with all slider values appearing to be set to 10.

ExamplePlugin shows this whenever you open its settings, even after you change the values:
![image](https://user-images.githubusercontent.com/1724041/66352159-ab16bf80-e924-11e9-8e0d-9c9820fda844.png)

If you set a max value lower than 10, no draggable element is displayed:
![image](https://user-images.githubusercontent.com/1724041/66352204-c255ad00-e924-11e9-8632-075e02835ec6.png)

Dragging the slider around *does* in fact change the value in the config file. The value then remains at the setting you applied, even after reopening the settings where it appears to be set to 10, until you drag the bar again.

**Comment by rauenzi** [comment]
I will double check this when I get home, I believe I fixed this in an update after this issue was opened and I never saw this. I had noticed this same issue.

**Comment by rauenzi** [comment]
This was fixed in a previous version: https://github.com/rauenzi/BDPluginLibrary/commit/0ebb1e3478862245fe7668d0c29ae6af00730d65#diff-e0e8f9f5eb85ae725b10f9cbf8a4f53d
