### ISSUE TITLE
keybind

### ISSUE THREAD

**Issue by Tharki-God** [rauenzi/BDPluginLibrary#130]
its easier if settings.keybind returns either the full code like `[0,162],[0,77]` or `ctrl+m`
the second option is much bettter because keycodes can be different thats why using `KeybindStore.toString( '[0,162],[0,77]' ).toLowerCase()` is much better option, this is keybindStore `WebpackModules.getByProps("keyToCode")` worthy enough to be added to discord modules

**Comment by Tharki-God** [comment]
Something i just noticed, how tf shall i clear the keybind?

**Comment by rauenzi** [comment]
Thanks for bringing this up, when I originally wrote this stuff a while ago they used the web standard codes and I never updated this for their own custom crap

**Comment by Tharki-God** [comment]
okay you have fixed the keybind in this but still haven't added a button to clear keybind
