### ISSUE TITLE
dropdowns

### ISSUE THREAD

**Issue by Tharki-God** [rauenzi/BDPluginLibrary#136]
drop downs are not fully shown and being cutdown and unable to select the options underneath 
![image](https://user-images.githubusercontent.com/73281112/183256501-9d077afa-d830-4893-a18e-7d7b65c18b7b.png)

**Comment by Tharki-God** [comment]
In short make the dropdowns scrollable

**Comment by rauenzi** [comment]
They always were scrollable, however developers were expected to set the height as needed, I have changed the default with the latest commit
