### ISSUE TITLE
Download link in README doesn't work

### ISSUE THREAD

**Issue by RobinRMC** [rauenzi/BDPluginLibrary#140]
The website does not exist anymore.

**Comment by Technetium1** [comment]
Can confirm
`https://betterdiscord.net/page/bouncy.php?&bpae=GbhGtCvmvUx7NYuomHFPTk%2FXEFfiA9V2INE1LuNeXh8HaZyD2jDDVYROkFc725t6tqxBxGAFFRbHZo%2F%2FFDmxmrFKMPnZXocVUIP6d6ogkzFCEz58OAA2BfZQTVu7NnECPSERL%2FU4Pdiv%2FTu1XeXjemvCrJfI3ZsXrvGgfxcxDXg92lCHMnXtvzGObBQODn101gaHL8tM1sl8HsykWLRAfw9YNN2opRliCQGB15c524OL3hoHfwYOOjBeOIxLx1ZaSVGJTZak9Gl5XlR8%2F1nQWfxPsC%2BLBq26YR1EA4hrqxsF8am8D5DavKfLQIewYmX16DJM6XQs2yynJQRy3tznmYhUY5AIEYNtPBQohK9jaX6PEqgb%2BOUCUS8D%2BL53oQksA8dAOUBygSgk9iCir3KGASEghor1y%2B82l2nyGMFzhnGcCQVBOpoHV1pXyKxekNANHG3yZM4u%2F1b7TknL3WpT6pME2iQ%2B%2F47qWiOISz%2FCn0Vj0cD69xy5EynoN1b4Ubqbo0VT35cX&redirectType=js&inIframe=false&inPopUp=false`
