### ISSUE TITLE
Pugins update notification only shows for a split second

### ISSUE THREAD

**Issue by JustOptimize** [rauenzi/BDPluginLibrary#141]
Since the last discord update the following notification it's only visible for a second
![image](https://user-images.githubusercontent.com/54294419/187078238-9811a03e-3fb3-4d46-ba96-c3e3a7de5ba4.png)
(If you click the button in time it still works but it's a bit of a hassle)

Os: Linux
Discord version: Ptb

**Comment by JustOptimize** [comment]
After half an hour of disabling plugins and restarting discord i finally found the faulty plugin...it was...**ServerCounter by DevilBro**
I don't even know why i had that plugin in the first plase, it isn't that useful eiter 🤦🏻‍♂️

Plugin repo: https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerCounter/

**Comment by JustOptimize** [comment]
It looks like the method `BDFDB.GuildUtils.rerenderAll();` is causing the issue

**Comment by Tharki-God** [comment]
well then report it to devil bro instead of here

**Comment by Technetium1** [comment]
@SmolAlli I confirmed it still happens with `ReadAllNotifications` disabled, trying to disable `ServerCounter` next, we'll see on the next updates if disabling that plugin does fix it.

**Comment by JustOptimize** [comment]
> well then report it to devil bro instead of here

Reporting on both sides, the issue appears on a feature of this library, not on devil's, if someone searches for the issue that someone will look here and not on a random plugin he doesn't know has a problem
