### ISSUE TITLE
UserInfoStore returns undefined

### ISSUE THREAD

**Issue by Pavel-Boyazov** [rauenzi/BDPluginLibrary#151]
ZLibrary.DiscordModules.UserInfoStore returns `undefined `after new discord update

**Comment by Strencher** [comment]
This is intentionally done by BetterDiscord's user credentials protection.

**Comment by Pavel-Boyazov** [comment]
Oh

**Comment by Pavel-Boyazov** [comment]
It's silly to ask this question here, but are there any other ways to get a token automatically? I don't use this for hacking or otherwise and the users of my product know that my plugin uses their token and for what

**Comment by Strencher** [comment]
No, our BD guidelines strictly disallow the direct access of the user's token. You won't get support with this stuff either. If you need the token for making an API call, I recommend using discord's builtin module for that (accessible via `DiscordModules.APIModule`).

**Comment by Pavel-Boyazov** [comment]
I forgot about them) Thanks you!

**Comment by Pavel-Boyazov** [comment]
> No, our BD guidelines strictly disallow the direct access of the user's token. You won't get support with this stuff either. If you need the token for making an API call, I recommend using discord's builtin module for that (accessible via `DiscordModules.APIModule`).

Where i can find more information about this module?

**Comment by Strencher** [comment]
Nowhere, you have to reverse engineer it to find out how it works.

**Comment by Pavel-Boyazov** [comment]
Ok. Thanks you again bro! You really help me <3

**Comment by Technetium1** [comment]
Close the issue.
