### ISSUE TITLE
discord crashes at launch

### ISSUE THREAD

**Issue by JJDelisle** [rauenzi/BDPluginLibrary#156]
since updating to zeres 2.07, everything is ruined.

**Comment by JJDelisle** [comment]
removed all my plugins and still broken. nice. broke the whole client.

**Comment by rauenzi** [comment]
This gives no information

**Comment by TheNickm2** [comment]
This is a BetterDiscord thing, has nothing to do with this plugin library. Reinstall BetterDiscord to fix your client.
