### ISSUE TITLE
Patcher instead still runs the original method

### ISSUE THREAD

**Issue by PatatjeMC** [rauenzi/BDPluginLibrary#157]
Hi, I've been trying to fix the MessageLoggerV2 plugin but the instead method for the patcher still runs the original method and obviously I can't call the origional function from the replacement code either.

Example:
```
this.unpatches.push(
      this.Patcher.instead(ZeresPluginLibrary.DiscordModules.MessageActions, 'deleteMessage', (_, args, original) => {
        const messageId = args[1];
        if (this.messageRecord[messageId] && this.messageRecord[messageId].delete_data) return;
        this.localDeletes.push(messageId);
        if (this.localDeletes.length > 10) this.localDeletes.shift();
        return original(...args);
      })
    );
```
This is a small portion of the MessageLoggerV2 plugin from before it broke. The original thing is now undefined and gives an error because of that and it still runs the original function.

**Comment by rauenzi** [comment]
The issue is already known and fixed for next release. Recommend you don't use plugins like that however.
