### ISSUE TITLE
ZLibrary.PluginUtilities.loadSettings converting arrays to objects

### ISSUE THREAD

**Issue by l0c4lh057** [rauenzi/BDPluginLibrary#16]
When I declare an object
```js
o = {
    "key1": [1,2,3,4],
    "key2": ["a","b","c","d"]
};
```
and then save the settings
```js
ZLibrary.PluginUtilities.saveSettings("foo", o);
```
The settings are correctly saved as arrays in the `foo.config.js`. But when I then load the settings
```js
o = ZLibrary.PluginUtilities.loadSettings("foo");
```
the arrays suddenly got converted to objects
```js
{
    "key1": {0:1,1:2,2:3,3:4},
    "key2": {0:"a",1:"b",2:"c",3:"d"}
}
```

The same problem exists for `loadData`.

**Comment by l0c4lh057** [comment]
As Arashiryuu pointed out the problem is in the `ZLibrary.Utilities.extend` function. I just checked that and when adding an array with that function it indeed converts the array to an object. The extend function is just iterating through the keys of the object and for an array those are the indices.
It would be great if a check gets added that does detect arrays and keeps them as an array.

**Comment by rauenzi** [comment]
This is on track to be fixed in the next version, I have it fixed locally. If you'd like to test it before it goes live, let me know.

**Comment by rauenzi** [comment]
I did test with the example you gave as well, seems to be okay to me: ![Preview](https://i.imgur.com/ShdEc1f.png)
