### ISSUE TITLE
ZeroPluginLibrary fails to update with the builtin betterdiscord update system.

### ISSUE THREAD

**Issue by PlayfulPiano** [rauenzi/BDPluginLibrary#161]
Been noticing this for the past two versions of ZeroPluginLibrary. Basically, whenever a new update of the plugin is available, I get the notice that well, a new update is available. So I click on "update all" in betterdiscord, and it loads like it updated. Except no plugin changelog is listed or other signs that it was successful. So I go to my plugins page in settings and it still shows up as the older version. And after a while, I get another notice that ZeroPluginLibrary has an update.

The only way I've gotten it to successfully update is if I did a manual download of the plugin file, and pasted it in my plugins folder. I'm not sure why it's unable to be updated within the betterdiscord client, but if you can please look into this!

**Comment by rauenzi** [comment]
"Update All" is a feature of this library, not betterdiscord, just to clarify.

**Comment by pianoboy8** [comment]
Oh, so is it like, basically the plugin that adds update all cannot update itself in said update all? Or is that still possible therefore the bug report is still justified?

**Comment by Klaex** [comment]
Having the same issue

**Comment by TwoPointInfinity** [comment]
everytime i try to update it says updated from 2.0.7 to 2.0.9 but then just minutes later i will have the option to update again and it will always be updating to 2.0.9 but never actually updates i guess.
