### ISSUE TITLE
keybind

### ISSUE THREAD

**Issue by Tharki-God** [rauenzi/BDPluginLibrary#162]
the keybind setting doesnt recognise pressed keybind and keybind store is now `WebpackModules.getModule(m => m.Kd.toString().includes("numpad plus"))`

**Comment by Tharki-God** [comment]
changing ```
const toCombo = modules__WEBPACK_IMPORTED_MODULE_1__.WebpackModules.getModule(m => m?.toString().includes("numpad plus")) ?? (() => [[0, 0], [0, 0]]);
const toEvent = modules__WEBPACK_IMPORTED_MODULE_1__.WebpackModules.getModule(m => m?.toString().includes("keyCode") && m?.toString().includes("BROWSER")) ?? (() => ({}));
```
to ```
const toCombo = modules__WEBPACK_IMPORTED_MODULE_1__.WebpackModules.getModule(m => m?.toString().includes("numpad plus"), {searchExports: true}) ?? (() => [[0, 0], [0, 0]]);
const toEvent = modules__WEBPACK_IMPORTED_MODULE_1__.WebpackModules.getModule(m => m?.toString().includes("keyCode") && m?.toString().includes("BROWSER"), {searchExports: true}) ?? (() => ({}));
```
would fix the keybind not being detected and you are converting the keybind to event on save but not event to keybind on load

**Comment by Tharki-God** [comment]
you should change it to array of combo and let it be

**Comment by Tharki-God** [comment]
or rather just leave the keycodes instead of converting them into anything

**Comment by rauenzi** [comment]
Keybinds will be redone by BD, I am not pursuing this any more.
