### ISSUE TITLE
Some stuff does not show up in options for https://github.com/riolubruh/YABDP4Nitro and we know that ZeresPluginLibrary is causing this

### ISSUE THREAD

**Issue by Pickymarker** [rauenzi/BDPluginLibrary#166]
Some stuff does not show up in options for https://github.com/riolubruh/YABDP4Nitro and we know that ZeresPluginLibrary is causing this 
![201907709-8d856291-f57a-4a92-a04e-e218699fee3b](https://user-images.githubusercontent.com/74084396/203167921-0c7a044a-03ea-4f31-9294-11d8ad0f01dc.png)
When it should look like this 
![image](https://user-images.githubusercontent.com/74084396/203168142-e6cd1505-dfa9-4c3e-8b85-3f537a46c8bb.png)

**Comment by SmolAlli** [comment]
Maybe don't advertise and give the link to an unofficial plugin that goes against BD's plugin guidelines.
Also, the accusatory tone isn't that nice.

**Comment by Pickymarker** [comment]
I was not trying to have a accusatory tone is was just saying that we tested the plugin and found the error has to do with ZeresPluginLibrary not the plugin and the creator of the plugin told me to contact the creator of ZeresPluginLibrary to get this fixed It has something do ZeresPluginLibrary we just don't know https://github.com/riolubruh/YABDP4Nitro/issues/36#issuecomment-1321257384

**Comment by riolubruh** [comment]
You should have just said that certain Settings elements such as textboxes don't always display properly, notably on Linux

**Comment by riolubruh** [comment]
Seems to be fixed with 94d202b.

**Comment by ZeddPerm** [comment]
> Seems to be fixed with [94d202b](https://github.com/rauenzi/BDPluginLibrary/commit/94d202bc8044b5bbf86ee0635395d36c0abbf040).

Was there a new update released for this? If not, how can I adjust my PluginLibrary so that it includes this fix?
