### ISSUE TITLE
Betterdiscord's updater is confused about version numbers

### ISSUE THREAD

**Issue by Cleridwen** [rauenzi/BDPluginLibrary#170]
Betterdiscord's built in updater is prompting me to update from 2.0.10 to 2.0.9:
![image](https://user-images.githubusercontent.com/25777291/205325670-52fe05b0-8845-4d11-b2fd-bada7f44a4cf.png)
computer moment

**Comment by thiaguinho4** [comment]
same

**Comment by jacket430** [comment]
Yeah same, I think discord might be seeing .10 as .1. You can temporarily stop the update notifications from showing up by changing the version number to 2.0.9 at the start of the library, at least until the next update.

**Comment by Pavel-Boyazov** [comment]
it happened because in-build version compare just compares strings. Strings in js compares character by character and js things that old version is 2.0.90

**Comment by Cleridwen** [comment]
Looks like BD 1.8.3 itself was updated with that in mind.
