### ISSUE TITLE
[BUG] Cant update plugins 

### ISSUE THREAD

**Issue by Tetrax-10** [rauenzi/BDPluginLibrary#171]
**Describe the bug**
Cant update plugins

**To Reproduce**
click update button

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75513645/208285123-ef721084-1f29-4b54-bf1e-3c716b3dcc2b.png)
![image](https://user-images.githubusercontent.com/75513645/208285127-fbf4afcb-4b3b-4c46-a3bd-84a621cf0abc.png)

**Discord Build (stable, ptb or canary):**
latest prob, idk where to see that

**Additional context**

**Comment by Strencher** [comment]
Plugin updates should be handled via BD's core updater, this seems like a bug of a different kind.

> latest prob, idk where to see that
At the bottom of your discord settings should be a version info section

**Comment by Tetrax-10** [comment]
Stable 164806 (c2a78f3)
should i report this bug in bd github page?
