### ISSUE TITLE
BetterDiscord prompts to update repeatedly every day but fails to actually update

### ISSUE THREAD

**Issue by rastafaa** [rauenzi/BDPluginLibrary#177]
"Successfully updated to .11 from .10" .. but the plugin stays on .10 so it prompts to update again about every hour.

Others confirmed they see the same issue.

**Comment by chozeur** [comment]
seems that i'm getting the same issue

**Comment by ruini1** [comment]
Just go to BetterDiscord settings and press updates, it should appear on the plugins tab. Just press update.

**Comment by rastafaa** [comment]
> Just go to BetterDiscord settings and press updates, it should appear on the plugins tab. Just press update.

It wasn’t updating for me I ended up having to manually replace it with the latest file from GitHub

**Comment by chozeur** [comment]
> Just go to BetterDiscord settings and press updates, it should appear on the plugins tab. Just press update.

thanks for the tip!

**Comment by rastafaa** [comment]
> Just go to BetterDiscord settings and press updates, it should appear on the plugins tab. Just press update.

It doesn't appear there. And the new .12 version still continuously prompts for update even though I'm on latest version. I press update and nothing happens.. and nothing appears in discord updates.

**Comment by ZenMasta** [comment]
Happening for me now as well but this only started after the better discord 1.85 updates and or possibly something to do with the zeres .12 update.


> > Just go to BetterDiscord settings and press updates, it should appear on the plugins tab. Just press update.
> 
> It doesn't appear there. And the new .12 version still continuously prompts for update even though I'm on latest version. I press update and nothing happens.. and nothing appears in discord updates.

**Comment by rauenzi** [comment]
Please update it manually in that case and then reload discord.

**Comment by rastafaa** [comment]
It's already updated though..
