### ISSUE TITLE
Crashing Discord (when attempting to modify messages?)

### ISSUE THREAD

**Issue by PennyJim** [rauenzi/BDPluginLibrary#179]
I'm not 100% certain it's this plugin library, but the 3 similar plugins I know that crash all use this library. Considering this issue seems fairly widespread, I would assume it's multiple libraries that are now broken.

The plugins that I've experienced this with are
- [BetterMessageLinks](https://github.com/TheGreenPig/BetterDiscordPlugins/tree/main/BetterMessageLinks)
- [BetterInvites](https://github.com/HypedDomi/BetterDiscordStuff/tree/main/Plugins/BetterInvites)
- [BetterSyntax](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/tree/main/BetterSyntax)

BetterMessageLinks crashes on load, so it might not be the library at fault there. Although, BetterInvites and BetterSyntax both crash discord when I try to load a channel that contains a message containing an invite or code block respectively.

**Comment by lil-fluff** [comment]
Confirmed on the BD discord server announcements, discord pushed some very breaking update today and Zeres Lib is definitely crashing :(

![image](https://user-images.githubusercontent.com/66636997/221703584-fb6c8d68-8641-4714-a0de-ce172ee6f61e.png)

**Comment by ggtylerr** [comment]
This is kinda unrelated, but the BD installer doesn't seem to disable plugins correctly. Even after seeing the logs say they disable plugins, all of mine are still loading in. I even tried manually removing ZeresPluginLibrary and some plugin automatically downloaded it and loaded it. Am I going to have to remove all my plugins for the time being?

**Comment by PennyJim** [comment]
> This is kinda unrelated, but the BD installer doesn't seem to disable plugins correctly. Even after seeing the logs say they disable plugins, all of mine are still loading in. I even tried manually removing ZeresPluginLibrary and some plugin automatically downloaded it and loaded it. Am I going to have to remove all my plugins for the time being?

If you know which ones use ZPL, then just remove those.
I removed all of them and then just kept adding them one at a time until discord crashed. Once it did, I removed it again, reloaded discord, and then tried other ones. It didn't catch all of the plugins (BetterInvites and BetterSyntax weren't immediately crashing), but as far as I can tell, the ones to watch out for are the ones altering how messages look at all.

**Comment by heyitzrare** [comment]
Confirmed, this is currently happening to me with:
- ActivityIcons
- BetterFormattingRedux
- VoiceActivity

**Comment by MirTeiwaz** [comment]
Identified this library as the cause of the crash. MIne crashes immediately upon launch.

**Comment by ThePhoenix576** [comment]
> Identified this library as the cause of the crash. MIne crashes immediately upon launch.

Same. i tried only loading this library and it crashes upon launch.
