### ISSUE TITLE
How do I get Message's React Component?

### ISSUE THREAD

**Issue by LeeJiaLe** [rauenzi/BDPluginLibrary#18]
I notice that currently when I do `Object.keys(ZLibrary.DiscordClasses.Messages)` it return `[]`

is there any alternative way to `Pathcer.before` Message component sent in discord?

**Comment by rauenzi** [comment]
You'll have to learn how to navigate Discord's internals and react tree yourself. The lib makes it easier, but it doesn't do it all for you, and tutorials like that are outside the scope of issues. You're free to join the Discord and ask relevant questions however.
