### ISSUE TITLE
Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by Dominikodz** [rauenzi/BDPluginLibrary#182]
After updates, plugin seems bugged :(
I think its about update notices not being able to hook to outdatedPlugins (?)
![obraz](https://user-images.githubusercontent.com/64926921/222991691-76dbc43b-14a2-4c6f-8393-2320b12cd4ca.png)

**Comment by rauenzi** [comment]
What plugins do you have installed?

**Comment by thegame4craft** [comment]
i've got this error multiple times and found out that this occours in `static showUpdateNotice(updateLink)`.

I found out that if you change lines 1885: 
```js
if (outdatedPlugins.querySelectorAll("span").length) outdatedPlugins.append(_domtools__WEBPACK_IMPORTED_MODULE_0__["default"].createElement("<span class='separator'>, </span>"));
```
to
```js
if (outdatedPlugins !== null && outdatedPlugins !== undefined) {
    if (outdatedPlugins.querySelectorAll("span").length) outdatedPlugins.append(_domtools__WEBPACK_IMPORTED_MODULE_0__["default"].createElement("<span class='separator'>, </span>"));
    outdatedPlugins.append(pluginNoticeElement);
}
```

The error won't occour again.

P.S. This needs check from others
