### ISSUE TITLE
Crashing on latest update

### ISSUE THREAD

**Issue by kapitanluffy** [rauenzi/BDPluginLibrary#185]
Here's the console

![image](https://user-images.githubusercontent.com/485799/227405709-d776ee35-d10c-46bc-a32c-057aac5844e4.png)

BetterDiscord v1.9.0
Discord Ptb 183451 (c90d5be) 
Host 1.0.1026 (30853) 
Windows 10 64-Bit (10.0.19044)

**Comment by rauenzi** [comment]
Looks like a BD error at the bottom

**Comment by maicol07** [comment]
Can confirm the same issue when enabling PluginRepo

**Comment by ArZeroNero** [comment]
Yes, crashes do happen if there is a library in the plugins. And the same happens with plugins that use this library.

**Comment by LockBlock-dev** [comment]
Full error message:
```
TypeError: Illegal invocation
    at Function.getModule (<anonymous>:4:46957)
    at Function.get ModalRoot [as ModalRoot] (<anonymous>:4:68549)
    at <anonymous>:4:73525
    at n.render (5fa680cfc6eecd74f1bf.js:2952)
    at Cs (5fa680cfc6eecd74f1bf.js:1748)
    at Rs (5fa680cfc6eecd74f1bf.js:1747)
    at gu (5fa680cfc6eecd74f1bf.js:1788)
    at Ic (5fa680cfc6eecd74f1bf.js:1780)
    at mc (5fa680cfc6eecd74f1bf.js:1780)
    at hc (5fa680cfc6eecd74f1bf.js:1779)
    at oc (5fa680cfc6eecd74f1bf.js:1776)
    at ic (5fa680cfc6eecd74f1bf.js:1775)
    at v (5fa680cfc6eecd74f1bf.js:1897)
    at D (5fa680cfc6eecd74f1bf.js:1898)
    at A.<computed> (e51fcade66a463b930ce.js:76)
    at k (e51fcade66a463b930ce.js:75)
    at MessagePort.j (e51fcade66a463b930ce.js:75)
```

**Comment by MiahFuta** [comment]
Same issue, ZeresPluginLibrary crashes discord, and any plugin that relies on it will also crash discord. Everything was working fine until I restarted my computer today for the first time in a week. I was previously on version 2.0.13 and I tried to downgrade to it, still every time I have the library or any plugin that relies on it in my plugin folder, discord crashes.

**Comment by tom-osborne** [comment]
It looks like this may be caused by an extra comma that was introduced in [b919d3809991138eeb9f322a55bb1d4ec7fc912c](https://github.com/rauenzi/BDPluginLibrary/commit/b919d3809991138eeb9f322a55bb1d4ec7fc912c)

The offending comma can be found in release/0PluginLibrary.plugin.js line 97

**Comment by Yentis** [comment]
Similar error for "getBulk" when "searchExports" is set to true:
```
BdApi.Webpack.getBulk({filter: module => {}, searchExports: true})

betterdiscord/renderer.js:4 Uncaught TypeError: Illegal invocation
    at Function.getBulk (betterdiscord/renderer.js:4)
    at Object.getBulk (betterdiscord/renderer.js:4)
    at <anonymous>:1:15
```

**Comment by ViLiDi230** [comment]
Try reinstalling (or repairing) BetterDiscord to 1.9.1. it solved problem to me

**Comment by tom-osborne** [comment]
> Same issue, ZeresPluginLibrary crashes discord, and any plugin that relies on it will also crash discord. Everything was working fine until I restarted my computer today for the first time in a week. I was previously on version 2.0.13 and I tried to downgrade to it, still every time I have the library or any plugin that relies on it in my plugin folder, discord crashes.
> 
>     * EDIT - Fixed via this: [[Bug] Discord instantly crash BetterDiscord/BetterDiscord#1580 (comment)](https://github.com/BetterDiscord/BetterDiscord/issues/1580#issuecomment-1483230357)

Can confirm following the steps in this link fixed the issue.

**Comment by GalaxJann** [comment]
> Try to reinstall (or repair) BetterDiscord to 1.9.1. it solved problem to me

Yes, the new BD-Update helped me too.

**Comment by Nobelium-XVIII** [comment]
Can confirm, BD 1.9.1 fixes the issue.

**Comment by CyborgArmGun** [comment]
On BD 1.9.2, issue reappears :/
