### ISSUE TITLE
What's going on with ZeresPluginLibrary

### ISSUE THREAD

**Issue by Nekonyx** [rauenzi/BDPluginLibrary#190]
It is updated literally every day. Why is this happening?

**Comment by flyingwolf79** [comment]
> It's currently at v2.0.15 for me and seems fine, redownload the latest version?

There is no current version available to download. I am showing 2.0.13 in my plugins folder.

**Comment by Technetium1** [comment]
Replace with this: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js

**Comment by lynrayy** [comment]
Yeah I'm tired of daily notification about update

**Comment by flyingwolf79** [comment]
> Yeah I'm tired of daily notification about update

The unsubscribe from updates.

**Comment by lynrayy** [comment]
The unsubscribe from updates. i dont know how

Just removed this plugin and nothing break. Good

**Comment by flyingwolf79** [comment]
> The unsubscribe from updates. i dont know how


In the upper-right corner of any page, click . In the left sidebar, under the list of repositories, select the "Manage notifications" dropdown menu and click Subscriptions. Select the notifications you want to unsubscribe from. In the top right, click Unsubscribe.

**Comment by lynrayy** [comment]
Im talking about this:
![image](https://user-images.githubusercontent.com/59417884/233749318-1929c1b4-773e-48da-a348-29a260a9af8e.png)

**Comment by flyingwolf79** [comment]
That's the plugin update in Better Discord. And is for a different plugin entirely.

Try doing some basic research, or perhaps this is too much for your current level of knowledge.

**Comment by mitchcapper** [comment]
i have idea what @flyingwolf79 is talking about.  The ZeresPluginLibrary is 100% the lib from this repo.  Yes it also seems like it can periodically have a problem updating  so it isn't that there are daily updates as much as an update issue.

As mentioned here generally manually replacing the plugin with the one from the repo will fix it.

**Comment by Technetium1** [comment]
The link I posted above to manually update past the broken version is the solution to this issue: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js

**Comment by flyingwolf79** [comment]
> i have idea what @flyingwolf79 is talking about. The ZeresPluginLibrary is 100% the lib from this repo. Yes it also seems like it can periodically have a problem updating so it isn't that there are daily updates as much as an update issue.

It turns out 2 weeks ago things were different. 

> 
> As mentioned here generally manually replacing the plugin with the one from the repo will fix it.

Yup, just at the time the download was removed for whatever reason, it is available now which is awesome.
