### ISSUE TITLE
Some default modules in the DiscordModules object are undefined

### ISSUE THREAD

**Issue by l0c4lh057** [rauenzi/BDPluginLibrary#20]
**Description**
When executing
```js
Object.entries(ZeresPluginLibrary.DiscordModules).filter(([a,b])=>b===undefined).map(([a,b])=>a)
```
you get a list of module names (how they are called in ZLib) that are not available anymore. In my case that is
```js
["GuildSync", "GuildActions", "ChannelSelector", "AccountManager", "CurrentUserIdle", "InviteResolver", "IconNames", "MessageParser", "OverlayUserPopoutSettings", "OverlayUserPopoutInfo", "DNDActions", "CurrentContext", "MediaDeviceInfo", "MediaEngineInfo", "VoiceInfo", "VideoStream", "TagInfo", "Tooltips", "UserProfileModal", "PrivacySettingsModal", "CreateInviteModal", "Avatar", "EmojiPicker", "ColorPicker"]
```
Weirdly when doing the same thing on `ZLibrary` instead of `ZeresPluginLibrary` ContextMenuItems﻿ is undefined too. I am not sure if that could be a caching issue and this exact module got fixed with the last library update and I still get the old version of the remote library. This might not be the case but I consider this a possible explanation. (At least if you still update the remote library version even though I already is deprecated for quite some time)

I am pretty sure that not all of the modules still exist but sure there are some that do exist. For example I am using the `GuildActions.requestMembers` function in one of my plugins and there still is a module with a `requestMembers` function that very much looks like it could have been the GuildActions module but the `markGuildAsRead` function the library is using to find the module does not exist anymore.
Currently I only know of that one module which still exists but I might try to find other modules too even though I currently don't know what other functions the modules had to check if they still exist.

Edit: I actually know of two modules, I just remembered that I was using the AccountManager module to get the account token in my plugin that would never become official and that function also still exists.

**Versions**
Stable 55865 (4f90d73)
Host 0.0.10
Linux 64-Bit (5.4.13-201.Fc31.X86_64)
BandagedBD 0.2.24 By Zerebos

**Comment by l0c4lh057** [comment]
I was just looking through my installed plugins looking for the used modules to see what functions they might have. This is what I found out:
```
GuildActions:    transitionToGuildSync, requestMembers
ChannelSelector: selectChannel
AccountManager:  forgotPassword, resetPassword (changed funtions to other ones in the same module)
InviteResolver:  resolveInvite
```
Those are the only modules used in the plugins I have on my computer, I could not find the other modules there.

**Comment by rauenzi** [comment]
Just cleaned this up in the latest update, thanks for letting me know!
