### ISSUE TITLE
Switch settings broken

### ISSUE THREAD

**Issue by DeCat4** [rauenzi/BDPluginLibrary#202]
![Capture](https://github.com/rauenzi/BDPluginLibrary/assets/57727851/5849dc87-2e5f-4ee0-b9d8-023331b304af)

Second categories and further do not open. The first one worked fine

**Comment by Dastan21** [comment]
![image](https://github.com/rauenzi/BDPluginLibrary/assets/58090137/a592329b-94c6-427f-a703-ab23148ec23d)
