### ISSUE TITLE
Discord still repeatedly demands an update when one doesn't exist

### ISSUE THREAD

**Issue by rastafaa** [rauenzi/BDPluginLibrary#205]
This issue is still present.. even though it's already updated. Constantly prompts for an update that doesn't exist. It only occurs with this plugin for some reason.

_Originally posted by @rastafaa in https://github.com/rauenzi/BDPluginLibrary/issues/181#issuecomment-1631326055_

**Comment by rauenzi** [comment]
Update manually and reload. This plugin no longer checks itself for updates.

**Comment by rastafaa** [comment]
Also I had already tried reloading it, didn't help, same issue came back

**Comment by Technetium1** [comment]
@rastafaa screenshot plugins page of fresh install with it happening

**Comment by rastafaa** [comment]
> @rastafaa screenshot plugins page of fresh install with it happening

![image](https://github.com/rauenzi/BDPluginLibrary/assets/37600342/6f87fc65-9412-482c-9321-6eb512e2fa3d)
![image](https://github.com/rauenzi/BDPluginLibrary/assets/37600342/3f262d82-9f22-4cfb-aa5f-2b662e262300)

**Comment by Technetium1** [comment]
@rastafaa Can you exit Discord, move the `BetterDiscord` folder from `%appdata%` or `.config` and reinstall BetterDiscord fresh, with only that plugin? Maybe BD cached something broken. That's my best guess.

**Comment by rauenzi** [comment]
Update manually
