### ISSUE TITLE
An error was encountered while trying to load this plugin

### ISSUE THREAD

**Issue by Peak20112** [rauenzi/BDPluginLibrary#206]
![image](https://github.com/rauenzi/BDPluginLibrary/assets/101064515/1e8836c2-a55d-40e5-a0ac-2a234c75eee5)
It gives this error when I installed AutoRichPresence

**Comment by kimizdevv** [comment]
I can confirm this error - I just started getting it as well. Did not install any other plugins and there doesn't seem to be any new Discord updates for me.

**Comment by rauenzi** [comment]
Is this on canary?

**Comment by Peak20112** [comment]
It is ptb

**Comment by rauenzi** [comment]
Discord seemingly released a bad build to canary/ptb which usually gets fixed in several (5+) hours and I only support stable anyways.

**Comment by Peak20112** [comment]
Ok thanks
