### ISSUE TITLE
An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by schietzzze** [rauenzi/BDPluginLibrary#214]
An error was encountered while trying to load this plugin. im no hackerman just a dirty end user pls help

![image](https://github.com/rauenzi/BDPluginLibrary/assets/149135514/fa3513cc-7202-4839-9f1d-dd731573b51f)

**Comment by gohamstergo** [comment]
https://github.com/rauenzi/BDPluginLibrary/issues/207
