### ISSUE TITLE
Plugin make discord crash when starting

### ISSUE THREAD

**Issue by Bricklou** [rauenzi/BDPluginLibrary#22]
I get this error when I try to run my discord for the Zere's Plugin library installed. If I removed it all work fine but almost the half of my plugins can't work anymore.

![image](https://user-images.githubusercontent.com/15181236/80452883-79e4f780-8927-11ea-9c98-dad3f1d92578.png)

**Comment by Bricklou** [comment]
I found the issue, this is EmojiUtilities which make discord crash. It seem that this plugin is not supported anymore by discord.

**Comment by rauenzi** [comment]
That's not quite what happened, but close.
