### ISSUE TITLE
ZeresPluginLib not loading

### ISSUE THREAD

**Issue by Smity1030** [rauenzi/BDPluginLibrary#233]
I get this error see attachment 0Lib,0Lib-1
![0Lib-1](https://github.com/user-attachments/assets/e4308a3a-b84d-416b-bd96-3e3a7ad81302)
![0Lib](https://github.com/user-attachments/assets/2003d846-cf8f-4bfd-99ba-f67e86c962d8)

**Comment by itmesarah** [comment]
Duplicate of #231
