### ISSUE TITLE
Modals.show(Alert/Confirmation)Modal isn't working

### ISSUE THREAD

**Issue by danny8376** [rauenzi/BDPluginLibrary#28]
Seems Discord changed something about ConfirmationModal, the current filter isn't able to find this modal anymore.(DiscordModules.ConfirmationModal becomes undefined.)

**Comment by rauenzi** [comment]
I already have a fix locally for the next version.

**Comment by rauenzi** [comment]
I'll try to release a version tomorrow containing the fix. Unfortunately, I've been very busy lately and there are a lot of bugs to fix.

**Comment by rauenzi** [comment]
@danny8376 Can you confirm this is fixed at latest level?
