### ISSUE TITLE
DiscordModules.Permissions.can no longer work

### ISSUE THREAD

**Issue by darten73** [rauenzi/BDPluginLibrary#31]
Permissions need to be like {data: 8n}

**Comment by rauenzi** [comment]
`DiscordModules.Permissions.can` (and really anything under `DiscordModules`) is an internal Discord function and not one provided by the library. Thus, it is subject to change at any time by Discord themselves and not documented as part of the library.

**Comment by darten73** [comment]
But it used in DiscordAPI.Channels
