### ISSUE TITLE
What's that ?

### ISSUE THREAD

**Issue by JeanOUINA** [rauenzi/BDPluginLibrary#34]
I searched a bit into ZeresPluginLibrary.js, and I found this: 
![image](https://user-images.githubusercontent.com/50077294/94066940-72018480-fded-11ea-88ad-c26c0712fae6.png)

Isn't it a bit dangerous, as the library bypass any restrictions inserted by bdd (https://github.com/rauenzi/BetterDiscordApp/blob/master/src/modules/v2.js#L27) by using its own webpack modules ? There are only sensitive infos inside, it can be used as a one liner by malicious plugins.
![image](https://user-images.githubusercontent.com/50077294/94067150-bab93d80-fded-11ea-977e-26ff0457362a.png)
ZeresPluginLibrary doesn't even use it, isn't it better to remove it and use UserStore instead ?

**Comment by rauenzi** [comment]
Sure I can remove it, but a nefarious plugin can get around BD's restrictions anyways by doing their own webpack module probe much like how the library does. I was planning to add a wrapper to my library's module search similar to the one added for BD, but that still leaves the same vulnerability.

I am working on adding some better protection in BD itself, but it's still being tested, and in the end JavaScript is very open and easy to break through things like sandboxing, proxies, prototypes, etc.

**Comment by msPornHub** [comment]
helo rauzenzi send nudes pls
