### ISSUE TITLE
Forced downgrade of ZeresPluginLibrary to version 1.0.2 on startup

### ISSUE THREAD

**Issue by IndieRockerBliss** [rauenzi/BDPluginLibrary#4]
When i noticed there's an update to version 1.0.4, so i decided to update it now. then the changelog for version 1.0.4 shows up. when i closed out on the first changelog, the second one appears but only time for the latest version which it's version 1.1.0 then i closed out that changelog then went ahead and updated once more and the same changelog for 1.1.0 from before shows up then closed it out again.

after all of the updating on that one plugin alone, i decided to restart Discord and see if it's going to keep [ZeresPluginLibrary](https://github.com/rauenzi/BDPluginLibrary/blob/master/release/0PluginLibrary.plugin.js) up-to-date, but after it finished loading it went back to version 1.0.2. which of course it's gonna repeat the new plugin update notification for [ZeresPluginLibrary](https://github.com/rauenzi/BDPluginLibrary/blob/master/release/0PluginLibrary.plugin.js) over and over every time if Discord is either restarted or booted on startup until there is a way to fix this issue for good.

**Comment by rauenzi** [comment]
I would suggest manually redownloading the library and deleting the config file `ZeresPluginLibrary.config.json`. I have never had anyone with this issue before and cannot reproduce on my end.

**Comment by IndieRockerBliss** [comment]
I've just now re-downloaded the plugin and the config file for said plugin and the Content errors shows that the plugin itself couldn't be compiled due to the META is not added in. 

![image](https://user-images.githubusercontent.com/37972220/48756373-f53c7700-ec66-11e8-9439-0088b08e973d.png)

So i tried to copy and paste the META from the broken version of the plugin and added the missing META onto the re-downloaded plugin, and when i restarted Discord i got a completely different error this time it won't compiled because of an unexpected token export.

![image](https://user-images.githubusercontent.com/37972220/48756604-d12d6580-ec67-11e8-9aab-856511d695aa.png)

**Comment by rauenzi** [comment]
It sounds like it was not downloaded correctly. Make sure you download the raw file or click this link: https://betterdiscord.net/ghdl?url=https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js

**Comment by IndieRockerBliss** [comment]
Okay now i've downloaded the plugin correctly this time, and of course after i restarted Discord new plugin update notification for ZeresPluginLibrary shows up again, since it's back to version 1.0.2 once again.

**Comment by rauenzi** [comment]
Redownload it, and don't click the update. Clearly there is something caching the wrong update url on your end since it doesn't exist in the current version of the plugin

**Comment by IndieRockerBliss** [comment]
so what i did is make another folder called plugins, while i've renamed the other folder to plugins.old and somehow the latest plugin of ZeresPluginLibrary seems to work fine alone. but i'm gonna see what causes to make that plugin revert to 1.0.2 on startup, it might take while for me to figure out.

**Comment by rauenzi** [comment]
Perhaps an alternate version of that plugin in the folder with a different filename, that could also cause it.

**Comment by IndieRockerBliss** [comment]
which right now i'm adding just one plugin back to the plugins folder from plugins.old and restart for each one.

**Comment by IndieRockerBliss** [comment]
hence the reason on why i'm trying to add back a plugin one by one in alphabetical order.

**Comment by IndieRockerBliss** [comment]
It took me a while to figure out, but i found out the `jsMaterialThemeCodeblocks.plugin.js` was the particular plugin that caused the issue in the first place, so i deleted it out from the plugins folder and now ZeresPluginLibrary can finally update smoothly.
