### ISSUE TITLE
Discord crashes whenever i put in the plugin library

### ISSUE THREAD

**Issue by Nullonos** [rauenzi/BDPluginLibrary#40]
Hey so I've downloaded the latest file of Zeres plugin library and every time I open discord and it loads Zeres plugin library it crashes discord I've checked with all other plugins its just Zeres nothing else happens besides discord crashing every time i reload it, don't really got any info besides that.

Thanks.

**Comment by Strencher** [comment]
Can you send screenshots of the error? (Open your console with `Ctrl + Shift + I` -> Select "Console" tab).

**Comment by Nullonos** [comment]
> Can you send screenshots of the error? (Open your console with `Ctrl + Shift + I` -> Select "Console" tab).

I was gonna do that and put the plugin back in the plugins library but now it works i don't know what was happening 10 hours ago but it works now sorry for troubling you.
