### ISSUE TITLE
0PluginLibrary & ZeresPluginLibrary not loading. Showing as account stealer/virus

### ISSUE THREAD

**Issue by SgtBreadStick** [rauenzi/BDPluginLibrary#43]
0PluginLibrary/ZeresPluginLibrary showing as an account stealer/virus on BandagedBD, causing most plugins not to work. 
This has only recently occurred.

![](https://i.sgtbrdstk.xyz/6shj0r.png)

**Comment by rojnwa** [comment]
Same goes for DevilBro's plugin library.

https://github.com/mwittrien/BetterDiscordAddons/issues/575

He simply said that his plugins are for BetterDiscord and not LightCord (which doesn't make much sense because Lightcord is simply using BetterDiscord)

**Comment by l0c4lh057** [comment]
> which doesn't make much sense because Lightcord is simply using BetterDiscord

This is made for BetterDiscord. We do not have to do with Lightcord in any way. If Lightcord decides to add some security layer that tries to catch token stealers that is a problem with Lightcord, not BetterDiscord or the plugin it detects. Just tell the Lightcord devs that their detection is shit.

**Comment by rauenzi** [comment]
Lightcord uses it's own private copy of BetterDiscord but the "security system" is from Lightcord not BD. As with DevilBro's library I make mine for BetterDiscord proper and do not support Lightcord. So this is a non-issue.
