### ISSUE TITLE
0PluginLibrary crashing client on load

### ISSUE THREAD

**Issue by whamer100** [rauenzi/BDPluginLibrary#48]
![image](https://user-images.githubusercontent.com/10352720/107083594-ba24b080-67aa-11eb-8806-055363fd6c95.png)
covered personal bits. i believe the bottom error is the main error. top error is an example of an error from TypingIndicator

**Comment by Strencher** [comment]
That's the typingindicator. Consider redownloading the plugin because the dev updated it recently.

**Comment by rauenzi** [comment]
The main error is coming from TypingIndicator as Strencher noted

**Comment by whamer100** [comment]
wow I'm actually surprised that was the entire crashing problem, thank you, i didn't realize there was an update
