### ISSUE TITLE
being spammed with update notifications

### ISSUE THREAD

**Issue by GalacticRuler** [rauenzi/BDPluginLibrary#5]
version 1.1.1, every time I open the window for discord, after dismissing the notification, it comes back.

**Comment by rauenzi** [comment]
Yeah it should come back in about two hours since you aren't on latest version. Dismissing is only temporary until next check.

**Comment by GalacticRuler** [comment]
Well, that's the thing, I've been checking for updates a lot; it's not downloading them

**Comment by rauenzi** [comment]
It doesn't automatically update them, it's still ultimately up to the user and as you said you just dismiss it instead of clicking the plugin name to update it.
