### ISSUE TITLE
[Bug] User popout blurred

### ISSUE THREAD

**Issue by andry08** [rauenzi/BDPluginLibrary#62]
**Which plugin/theme is this about?**
AccountDetailsPlus v0.1.10
ZeresPluginLibrary v1.2.29

**Describe the Bug**
When I open the account details, it shows up a bit blurred.

**To Reproduce**
1. Set your zoom level to 90% (I use discord like this)
2. Open your account details popup as you usually do.

**Expected Behavior**
It should be clear as the original one (opening a normal user popup works as intended)

**Screenshots**
![abc123](https://user-images.githubusercontent.com/10282315/115268508-a0a0cd00-a13a-11eb-9fff-d860eeeff367.png)

**Discord Version**
Stable 82590 (bf3e4f7)
BD 1.0.0 (stable)

**Additional Context**
The screen where I have discord is a normal 1080p, I use discord with a 90% zoom level. This bug doesn't seem to appear at 100% zoom level and I haven't tested other levels.
After a bit of tinkering with the devtools I tried removing the transform attribute and it fixed it (but it obviously goes in the wrong position), and in the screenshot you can see the before and after.
I opened this issue here, but it might have been more relevant in the BDPluginLibrary repo, as in the plugin you only seem to call a function in the library.
I suggest removing the inline style translate attribute, and fixing the top/left offset calculations to compensate for that. This should fix this issue.

**Comment by rauenzi** [comment]
This is an issue with the account details plugin not the library. The plugin is the one that needs to make sure the transform is not occurring on half pixels.
