### ISSUE TITLE
Popouts.showUserPopout causes crashing

### ISSUE THREAD

**Issue by QbDesu** [rauenzi/BDPluginLibrary#71]
~~A recent update seems to have changed how the `DiscordModules.PopoutOpener.openPopout` method works. As a result a couple of plugins that use `Popouts.showUserPopout` to crash now. This includes RoleMembers (to name one of yours) and TypingUsersAvatars and probably a couple of  others. (nevermind this I was probably just calling it wrong)~~
`WebpackModules.getByDisplayName("ConnectedUserPopout")` so by extension `DiscordModules.UserPopout` is undefined which is what causes the crash in the end.

https://github.com/rauenzi/BetterDiscordAddons/issues/426
https://github.com/QWERTxD/BetterDiscordPlugins/issues/50

**Comment by rauenzi** [comment]
This is now fixed thanks to Stencher
