### ISSUE TITLE
ZeresPluginLibrary crashing BD

### ISSUE THREAD

**Issue by iamqw3rty** [rauenzi/BDPluginLibrary#75]
A new update was released for ZeresPluginLibrary, I go to install it, Discord restarts and I get an error message saying "BetterDiscord seems to have crashed your Discord client" or something like that.
![image](https://user-images.githubusercontent.com/87212071/125143921-36207d00-e0ea-11eb-91ee-3e85ff5201c7.png)

**Comment by rauenzi** [comment]
You need to manually install this update because that's the exact issue this update fixes.
