### ISSUE TITLE
BD crashes if i try to update the plugin.

### ISSUE THREAD

**Issue by scolastico** [rauenzi/BDPluginLibrary#76]

**Comment by justicelock1** [comment]
same

**Comment by kolva3** [comment]
same

**Comment by kolva3** [comment]
yeah when i try to update the library i have to reinstall BD

**Comment by Gellyboy** [comment]
@kolva3 if you just close discord through task manager, you don't have to reinstall BD

**Comment by strwbzzy** [comment]
The same thing happened to me this morning while trying to update the library.

**Comment by rauenzi** [comment]
See #74 you need to update manually
