### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by priyanshuop** [rauenzi/BDPluginLibrary#79]
The latest update pushed is immediately crashing the discord whenever i click the update button

**Comment by Slegnor** [comment]
Can confirm, as soon as I update from the titlebar notification, Discord crashes and auto-reloads normal Discord until the next launch.

![image](https://user-images.githubusercontent.com/11891577/125159355-cbfdeb80-e16e-11eb-9a65-ca580f43d8d1.png)

![image](https://user-images.githubusercontent.com/11891577/125159342-bb4d7580-e16e-11eb-8bb5-163bc48b6d27.png)

**Comment by grimmyxx** [comment]
yep, same thing here.

**Comment by Zwoider** [comment]
Same here

**Comment by skoki2** [comment]
#75

**Comment by SaharshDaNerd** [comment]
What I did was install Plugin Repo and clicked on outdated and just updated it.

**Comment by rauenzi** [comment]
Please read previous issues
