### ISSUE TITLE
Will not stop crashing.

### ISSUE THREAD

**Issue by morbidrot** [rauenzi/BDPluginLibrary#80]
Every time i try to install the new update betterdiscord crashes discord and i have to reinstall betterdiscord to discord, it's pretty annoying. If it's a problem with the plugin library it should be looked at but if it's a problem with betterdiscord then, not much you can do i suppose. I tried running repairs and reinstalling BD multiple times, didn't do anything.

**Comment by artemOP** [comment]
Similar issue here, installed the new update successfully but am unable to update `ZeresPluginLibrary` even with all other plugins and themes removed. Upon Clicking update plugin it just instantly crashes

**Comment by GoogleMaster** [comment]
dublicate #75

**Comment by rauenzi** [comment]
Read any of the several previous issues
