### ISSUE TITLE
BetterDiscord Crashing

### ISSUE THREAD

**Issue by CommanderChef** [rauenzi/BDPluginLibrary#81]
I've received an update notification, but everytime I click on it. BetterDiscord crashes.

**Comment by Peleret** [comment]
Same issue as #75 
Just install it manually instead

**Comment by goldsonic** [comment]
Is there a mirror for this I am unable to access the site to pull it manually.

**Comment by AeroXV** [comment]
Same as above. Download link leads to a 408 Request Time-out.

**Comment by Hartsai** [comment]
the link for me was dead as well but if you parse it a bit you can actually open the file. Now I'm not linking anything here but you can also find the link if you edit/open the 0PluginLibrary.plugin.js file in plugins folder and look for the first lines in code where it says source - and the url for the source. I copy pasted the code in url to the file and saved and that fixed it for me

**Comment by goldsonic** [comment]
> the link for me was dead as well but if you parse it a bit you can actually open the file. Now I'm not linking anything here but you can also find the link if you edit/open the 0PluginLibrary.plugin.js file in plugins folder and look for the first lines in code where it says source - and the url for the source. I copy pasted the code in url to the file and saved and that fixed it for me

This is the solve

**Comment by AeroXV** [comment]
> the link for me was dead as well but if you parse it a bit you can actually open the file. Now I'm not linking anything here but you can also find the link if you edit/open the 0PluginLibrary.plugin.js file in plugins folder and look for the first lines in code where it says source - and the url for the source. I copy pasted the code in url to the file and saved and that fixed it for me

Thanks for the tip. Fixed for me as well.

**Comment by HolidayTheBoi** [comment]
Also if anyone reading this couldn't figure out exactly what Hartsai meant like me, you can also just find the plugin on the Betterdiscord site and download it from there because it's updated on there: [https://betterdiscord.app/plugin/ZeresPluginLibrary](https://betterdiscord.app/plugin/ZeresPluginLibrary)

**Comment by efadfa3** [comment]
I wish I had seen this solve before I had deleted the library files cause they were simply crashing my BD. Therefore, there is no fix once you don't have the file anymore and I am still waiting for a mirror.

**Comment by jack652** [comment]
link to download the file @efadfa3 https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js

**Comment by TanyaSapien** [comment]
> the link for me was dead as well but if you parse it a bit you can actually open the file. Now I'm not linking anything here but you can also find the link if you edit/open the 0PluginLibrary.plugin.js file in plugins folder and look for the first lines in code where it says source - and the url for the source. I copy pasted the code in url to the file and saved and that fixed it for me

> link to download the file @efadfa3 https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js

STOP SCROLLING, ANONYMOUS USER, THIS IS THE FIX!
I had the same crashing issue, copypasted from browser into text editor and saved, everything's running fine now.

**Comment by Crusher214** [comment]
> the link for me was dead as well but if you parse it a bit you can actually open the file. Now I'm not linking anything here but you can also find the link if you edit/open the 0PluginLibrary.plugin.js file in plugins folder and look for the first lines in code where it says source - and the url for the source. I copy pasted the code in url to the file and saved and that fixed it for me

which link to i replace it with?

**Comment by Skip75** [comment]
> 
> 
> > the link for me was dead as well but if you parse it a bit you can actually open the file. Now I'm not linking anything here but you can also find the link if you edit/open the 0PluginLibrary.plugin.js file in plugins folder and look for the first lines in code where it says source - and the url for the source. I copy pasted the code in url to the file and saved and that fixed it for me
> 
> > link to download the file @efadfa3 https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
> 
> STOP SCROLLING, ANONYMOUS USER, THIS IS THE FIX!
> I had the same crashing issue, copypasted from browser into text editor and saved, everything's running fine now.

Exact. Open Discord -> Ignore update -> User Settings -> Plugins -> edit 'ZeresPluginLibrary' (blue pencil button) -> paste here the lines copied from above URL page. It's fixed.

Just a mess having to do it manually.

**Comment by efadfa3** [comment]
> > > the link for me was dead as well but if you parse it a bit you can actually open the file. Now I'm not linking anything here but you can also find the link if you edit/open the 0PluginLibrary.plugin.js file in plugins folder and look for the first lines in code where it says source - and the url for the source. I copy pasted the code in url to the file and saved and that fixed it for me
> > 
> > 
> > > link to download the file @efadfa3 https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
> > 
> > 
> > STOP SCROLLING, ANONYMOUS USER, THIS IS THE FIX!
> > I had the same crashing issue, copypasted from browser into text editor and saved, everything's running fine now.
> 
> Exact. Open Discord -> Ignore update -> User Settings -> Plugins -> edit 'ZeresPluginLibrary' (blue pencil button) -> paste here the lines copied from above URL page. It's fixed.
> 
> Just a mess having to do it manually.

Or you know, just open the raw file and press ctrl+s to save the whole page as a plugin and add it in without having to copy anything.

**Comment by Hartsai** [comment]
> > the link for me was dead as well but if you parse it a bit you can actually open the file. Now I'm not linking anything here but you can also find the link if you edit/open the 0PluginLibrary.plugin.js file in plugins folder and look for the first lines in code where it says source - and the url for the source. I copy pasted the code in url to the file and saved and that fixed it for me
> 
> which link to i replace it with?

I'm sure you have already figured it out by other answers or yourself. What I meant was to open that 0PluginLibrary.plugin.js and look for the website url for the source. Open that website in browser and copy the whole code to clipboard. Replace everything in the 0PluginLibrary.plugin.js file with what you just copied in clipboard and save.

People above have already linked for the page too. I guess I just don't believe enough people to open unknown sources and that's why I didn't post the link in the first place.

**Comment by xkxtinctt** [comment]
Hi guys. I'm really experienced with computers and tech, however I do not understand at all what I am supposed to do to fix this. Could someone please use really simple language to explain how to fix BD crashing when I try to update ZeresPluginLibrary? I don't know why I'm even confused lol but help please. (A contributing factor could be i am substantially under the influence of the devils lettuce in my current situation)

**Comment by rauenzi** [comment]
Reinstalling BD should also fix this issue.
