### ISSUE TITLE
the plugin library now crashes betterdiscord everytime the plugin is in the plugins folder, and the download link from this github is broken

### ISSUE THREAD

**Issue by jack652** [rauenzi/BDPluginLibrary#86]

**Comment by toth-Daniel** [comment]
same here :(

**Comment by telumletiferum** [comment]
The crash is actually related to BDFDB. Reinstall that and it should work prob. For me it did

**Comment by David8985** [comment]
same here

**Comment by A983Hub** [comment]
For me it didn't. I reinstalled it and everything's now back to normal! However ZeresPluginLibrary created some UI Issues.
