### ISSUE TITLE
Add default value to FilePicker, Directory-only as an option to FilePicker, and other suggestions

### ISSUE THREAD

**Issue by CompletelyUnbelievable** [rauenzi/BDPluginLibrary#9]
The setting module's FilePicker ([docs](https://rauenzi.github.io/BDPluginLibrary/docs/module-Settings.FilePicker.html)) has an issue where there is no option to have a default directory. 

- Allowing the change of the placeholder value and the text on the button would be good for plugin developer choice and would allow plugin developers to provide translations.

FilePicker also only has the ability to select files, with no capability to select directories.

- When selecting a directory it should show the directory for it in the settings panel instead of just the foldername. The version you provided me earlier only showed the foldername.

- Being able to manually edit the text for the directory would be nice to have, but isn't required. Currently clicking anywhere on the FilePicker will open the dialog box, even if you click on the textarea.

**Comment by rauenzi** [comment]
Not sure why this was closed... Opening...

**Comment by CompletelyUnbelievable** [comment]
Sorry about that, I figured that if this hasn't gotten a response in about 8 months that I might have submitted it to the wrong place.

**Comment by rauenzi** [comment]
Accepted the PR by @SimplyLinn which will allow some more options for the filepicker. That only addresses some of this, but it's a start.

**Comment by rauenzi** [comment]
At this point, I will not be adding this.
