### ISSUE TITLE
Channel.sendMessage doesn't work and prints error on console.

### ISSUE THREAD

**Issue by tfanfy** [rauenzi/BDPluginLibrary#91]
Steps to reproduce: 
1. Call Channel.sendMessage with any guild channel
2. Look at the console
![image](https://user-images.githubusercontent.com/53312672/128707085-ea60dcef-7d84-4b94-b51b-74c5d86a8afb.png)
Plugin version 1.2.31

**Comment by rauenzi** [comment]
The DiscordAPI module has been discontinued and deprecated for a long time, this is a wontfix
