### ISSUE TITLE
0PluginLibrary.plugin.js causing crashes on load

### ISSUE THREAD

**Issue by d347h-n3k0** [rauenzi/BDPluginLibrary#95]
File Version: 1.2.31
Discord Version: Stable 93958 (486a541)
BetterDiscord Version: 1.2.1

Reinstalled plugin after the update fix.
As soon as Discord (BetterDiscord) load up the Plugin seems to cause BetterDiscord to crash.
After removing BetterDiscord works again.
Asked some other people and they seem to have the same issue.
First crash appered random over the day after that the plugin crashed. Clean reinstall has been made but random crash after about 1h and same thing again after it.

**Comment by rauenzi** [comment]
The plugin has already updated to fix this with version 1.2.32

**Comment by d347h-n3k0** [comment]
Oh thanks fo the information probably happened after my my clean re install then
